### ISSUE TITLE
Admob Uygulama ID'sini girme

### ISSUE THREAD

**Issue by myilmaz07** [MrNtlu/WebviewProject#1]
Yaptığıın her şey çok güzel olmuş ellerine sağlık ama android studioya yeni başlayan 16 yaşında biri olduğum için senin klavuzda gösterdiğin yerlere banner ID'si gelmesi gerekiyor peki admob uygulama IDmizi nereye gireceğiz yardımcı olursan çok sevinirim:D
Bir de sadece firebasede fln talimat uygulamadan direk onsignal ID'mizi mi gireceğiz yoks firebase dosyasını falan yükleyecek miyiz ?

**Comment by MrNtlu** [comment]
Geç gördüm kusura bakma, uzun zaman sonra güncelleme fırsatım oldu, uygulama ID'si için gereken yeri de ekledim. Dökümantasyona da ekleyeceğim birazdan. OneSignal setup tutorialını takip etmen yeterli. Ben öyle yapmıştım çünkü şuanda hatırlamıyorum neleri indirdiğimi.

**Comment by myilmaz07** [comment]
Iyi yapmışsin en kısa sürede deneyeceğim klavyene sağlık

21 Oca 2020 Sal 21:40 tarihinde Burak <notifications@github.com> şunu yazdı:
